stages:
  - compile
  - build
  - test
  - deploy

variables:
  GCP_PROJECT_ID: "extractor-backend"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

image: docker:latest
services:
  - docker:dind

# security testing: https://docs.gitlab.com/ee/user/application_security/
# According to gitlab doc, this is the way to go.. so let's do this!
# include:
#  - template: Security/Dependency-Scanning.gitlab-ci.yml
#  - template: Security/Secret-Detection.gitlab-ci.yml

cache:
  key: "$CI_COMMIT_REF_NAME"
  policy: push
  paths:
    - build
    - .gradle

compile:
  image: gradle:8.4.0-jdk17
  stage: compile
  script:
    - gradle compileJava


build:
  image: gradle:8.4.0-jdk17
  stage: build
  script:
    - gradle clean bootBuildImage

test:
  image: gradle:8.4.0-jdk21
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: ./build/test-results/test/**/TEST-*.xml

deploy:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  before_script:
    - >
      az login 
      --service-principal 
      -u $AZURE_SERVICE_PRINCIPAL 
      -p $AZURE_CLIENT_SECRET 
      --tenant $AZURE_TENANT
    - az extension add --name containerapp --upgrade
  script:
    - tag=$CI_COMMIT_REF_NAME
    # az containerapp up documentation: https://docs.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-up
    - >
      az containerapp up 
      --name extractor-backend
      --resource-group thubehhuh 
      --location westeurope 
      --environment integration5
      --target-port 8080
      --ingress external
      --image "integration5.azurecr.io/extractor-backend:latest"
      --registry-username $AZURE_CR_USERNAME
      --registry-password $AZURE_CR_PASSWORD
    - >
      az containerapp update 
      --name extractor-backend 
      --resource-group thubehhuh
      --cpu 1
      --memory 2Gi
      --min-replicas 0
      --max-replicas 1
      --replace-env-vars \
        'EXTRACTOR_LOGGING_LEVEL'='DEBUG' \
        'EXTRACTOR_MYSQL_HOST'=$EXTRACTOR_MYSQL_HOST \
        'EXTRACTOR_MYSQL_DATABASE'=$EXTRACTOR_MYSQL_DATABASE \
        'EXTRACTOR_MYSQL_USER'=$EXTRACTOR_MYSQL_USER \
        'EXTRACTOR_MYSQL_PASSWORD'=$EXTRACTOR_MYSQL_PASSWORD \
        'EXTRACTOR_APP_PORT'=$EXTRACTOR_APP_PORT \
        'EXTRACTOR_DB_PORT'=$EXTRACTOR_DB_PORT \
        'EXTRACTOR_SPRING_PROFILE'='prod' \
        'KEYCLOAK_HOST'=$KEYCLOAK_HOST \
        'KEYCLOAK_PORT'=$KEYCLOAK_PORT \
        'KEYCLOAK_ADMIN'=$KEYCLOAK_ADMIN \
        'KEYCLOAK_ADMIN_PASSWORD'=$KEYCLOAK_ADMIN_PASSWORD \
        'RABBIT_MQ_DEFAULT_USER'=$RABBIT_MQ_DEFAULT_USER \
        'RABBIT_MQ_DEFAULT_PASS'=$RABBIT_MQ_DEFAULT_PASS \
        'RABBIT_MQ_HOST'=$RABBIT_MQ_HOST \
        'RABBIT_MQ_PORT'=$RABBIT_MQ_PORT \
        'RABBIT_MQ_VIRTUAL_HOST'=$RABBIT_MQ_VIRTUAL_HOST \
        'API_KEY_TELRAAM'=$API_KEY_TELRAAM

        
      # only:
      # - tags


 
