logging.level.be.kdg.integration5.extractor: ${EXTRACTOR_LOGGING_LEVEL}
spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect