logging.level.root: DEBUG
spring:
    jpa:
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQLDialect

    rabbitmq:
        host: ${RABBIT_MQ_HOST}
        port: ${RABBIT_MQ_PORT}
        username: ${RABBIT_MQ_DEFAULT_USER}
        password: ${RABBIT_MQ_DEFAULT_PASS}

    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://${KEYCLOAK_HOST}/realms/extractor-configurator-realm/protocol/openid-connect/certs
                    issuer-uri: http://${KEYCLOAK_HOST}/realms/extractor-configurator-realm
